// // <copyright file="SettingsData.cs" company="PublicDomain.com">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />

namespace PublicDomain
{
    // Directives
    using System;
    using System.Collections.Generic;
    using System.Drawing;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:Urlister.UrlisterSettings"/> always on top.
        /// </summary>
        /// <value><c>true</c> if always on top; otherwise, <c>false</c>.</value>
        public bool AlwaysOnTop { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> remember location.
        /// </summary>
        /// <value><c>true</c> if remember location; otherwise, <c>false</c>.</value>
        public bool RememberLocation { get; set; } = true;

        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        /// <value>The location.</value>
        public Point Location { get; set; }

        /// <summary>
        /// Gets or sets the link regex.
        /// </summary>
        /// <value>The link regex.</value>
        public string LinkRegex { get; set; } = @"javascript:SetCfpId\((?<cfpid>\d+)\)";

        /// <summary>
        /// Gets or sets the launch regex.
        /// </summary>
        /// <value>The launch regex.</value>
        public string LaunchRegex { get; set; } = @"https://www.ancestry.co.uk/family-tree/tree/12345678/family/familyview?cfpid=${cfpid}";
    }
}